<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form generated by database</title>
</head>
<body>
    <?php
    $connection = new mysqli("localhost","root","","formdatabase");
    $raw_result = mysqli_query($connection, "SELECT * FROM config_example ORDER BY ID_PorzadekWyswietlania ASC");
    ?>
    <div id="container">
    <form action="yourfile.php" method="post">
        <?php
            while($result = mysqli_fetch_array($raw_result)){
                echo "<label>".$result['NazwaDlaUzytkownika']."<input type=".$result['TypPola']." name=".$result['NazwaPola']." id=".$result['IDPola_Stylizacja']."></label><br>";
            }
        ?>
    <input type="submit" value="Submit">
    </form>
    </div>
</body>
</html>